name: ActiveSG Gym Capacity Scraper

on:
  schedule:
    # Run every hour from 6 AM to 11 PM Singapore time (UTC+8)
    # In UTC: 22:00 (6 AM SGT) to 15:00 next day (11 PM SGT)
    - cron: "0 22-23,0-15 * * *"

  # Allow manual trigger
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add gym_capacity_data.json
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update gym capacity data - $(date)"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/tortillatiff/gym-scraper.git HEAD:main
          fi

      - name: Upload data as artifact (backup)
        uses: actions/upload-artifact@v4
        with:
          name: gym-capacity-data
          path: gym_capacity_data.json
          retention-days: 30
