name: ActiveSG Gym Capacity Scraper

on:
  schedule:
    # Run every hour from 6 AM to 11 PM Singapore time (UTC+8)
    - cron: "0 22,23,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21 * * *"

  # Allow manual trigger
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Update gym capacity data - ${{ github.run_id }}'
          file_pattern: 'gym_capacity_data.json'

      - name: Upload data as artifact (backup)
        uses: actions/upload-artifact@v4
        with:
          name: gym-capacity-data
          path: gym_capacity_data.json
          retention-days: 30
